****************************************
* Program name : FB.PROC.REST
* Author       : Greg Bino
* Date written : March 14, 2019
* Library      : FBBP
* COPYRIGHT (c) : AFS, LLC 2019, All Rights Reserved.
*
*
* Last updated by afs (AFSLOGISTICS\gbino) at 06:35:53 on 05/15/2019.
*
* Start modification history
* Mod nn  mm/dd/yy, init, req #, description

* End modification history
*
*******************************************

      UPL.VIN = 'FBBP' ; UPL.VIN<2> = 'FB.PROC.REST' ; UPL.VOUT = ''
      CALL GET.USER.NEW(USER,CH.NUM)
      UPL.VIN<3> = USER
      UPL.VIN<4> = CH.NUM
      **     CALL UPD.PROGRAM.LOG(UPL.VIN,UPL.VOUT)
      **     CALL GET.SERVER.INFO(SVR.VIN,SVR.VOUT)
***      SVR.NAME=SVR.VOUT<1>
      BEGIN CASE
         CASE USER='DAVID'
         CASE USER = "GBINO"
         CASE USER = "NMEDDAUGH"         ; * NKH01
         CASE USER='SV.UVAUTO'
         CASE USER='UVTASKS'
         CASE 1
            CRT "YOU ARE NOT AUTHORIZED TO USE THIS PROGRAM"
            STOP
      END CASE

      VIN1=""
      VIN1<1> = "FB.PROC.REST"
      VIN1<2> = USER
      VIN1<3> = SYSTEM(18)
      VIN1<4> = "S"
      **    CALL PROGTRACK(VIN1,VOUT1)
      GET (ARG.,1) OBEG.DATE THEN
         BEG.DATE=ICONV(OBEG.DATE,'D')
      END ELSE
         BEG.DATE=DATE()
      END
      GET (ARG.,2) OEND.DATE THEN
         END.DATE=ICONV(OEND.DATE,'D')
      END ELSE
         END.DATE=DATE()
      END
      CRT @(0,0):@(-1):@(0,3):'FB.PROC.REST - Processing Clients from ':BEG.DATE'D2/':' to ':END.DATE'D2/':'...'
      GOSUB OPEN.FILES

      GET (ARG.,3) CLIENT.LIST.NAME ELSE CLIENT.LIST.NAME=''
      GET (ARG.,4) OPT.LIST ELSE OPT.LIST=''
      GET (ARG.,5) START.TIME ELSE START.TIME=''
      IF START.TIME#'' THEN
         CRT "Waiting until ":START.TIME
         STMT="SLEEP ":START.TIME
         EXECUTE STMT CAPTURING TIME.RESULTS
      END

      IF CLIENT.LIST.NAME#'' AND CLIENT.LIST.NAME#'ALL' THEN
         STMT='GET-LIST ':CLIENT.LIST.NAME
      END ELSE
         STMT='SSELECT CLIENTS WITH OCR = "Y"'
      END
      EXECUTE STMT RTNLIST CLIENT.LIST CAPTURING RESULTS
      NUM.CLIENTS=@SELECTED

      DIM BILL.REC(300),CLIENT.REC(350)
      MAT BILL.REC = '' ; MAT CLIENT.REC =''

      NULL=""
      TOT.NUM.BILLS=0
      ERROR.CNT=0
10:   ERRORS=''

*************************** CLIENT LOOP
      CLIENT.EOF=0
      CLIENT.CNT=0
      CLIENT.PER=0
      LOOP
         READNEXT CLIENT.ID FROM CLIENT.LIST ELSE CLIENT.EOF=1
      UNTIL CLIENT.EOF DO
         CLIENT.CNT+=1
         CLIENT.PCT=ICONV(CLIENT.CNT/NUM.CLIENTS*100,'MR2')
         MATREAD CLIENT.REC FROM F.CLIENT,CLIENT.ID THEN
            CRT @(0,5):@(-4):CLIENT.CNT'R#4':' - ':CLIENT.PCT'R26#6':'% ':CLIENT.ID:' - ':CLIENT.REC(2)

**            IF CLIENT.REC(70)<1,6> # "Y" THEN CONTINUE
            OPEN '','FB.BILLS.HIST,':CLIENT.ID TO F.BILL THEN

               STMT = 'SELECT FB.PROC.DATE.XREF,':CLIENT.ID
               STMT:=' WITH DATE GE "':OCONV(BEG.DATE,'D2/'):'"'
               STMT:=' AND WITH DATE LE "':OCONV(END.DATE,'D2/'):'"'
               EXECUTE STMT RTNLIST DT.LIST CAPTURING OUTPUT

               IF @SELECTED < 1 AND CLIENT.ID # "00000" THEN GOTO SKIP.CLIENT
               STMT = 'QSELECT FB.PROC.DATE.XREF,':CLIENT.ID
               EXECUTE STMT PASSLIST DT.LIST RTNLIST NDX.LIST CAPTURING OUTPUT

               IF @SELECTED < 1 AND CLIENT.ID # "00000" THEN GOTO SKIP.CLIENT
               IF CLIENT.ID="00000" THEN
                  STMT='SELECT FB.BILLS.HIST,':CLIENT.ID
                  STMT:=' WITH VERSION = "0"'
                  **      STMT:=' AND WITH 39 # "R"'
                  STMT:=' AND WITH 39 # "P"'
                  STMT:=' AND WITH 30 GE "':OCONV(BEG.DATE,'D2/'):'"'
                  STMT:=' AND WITH 30 LE "':OCONV(END.DATE,'D2/'):'"'
                  EXECUTE STMT RTNLIST BILL.LIST CAPTURING OUTPUT
               END ELSE
                  STMT='SELECT FB.BILLS.HIST,':CLIENT.ID
***                  STMT:=' WITH VERSION = "0"'
                  **        STMT:=' AND WITH 39 # "R"'
                  STMT:=' AND WITH 39 # "P"'
                  STMT:=' AND WITH 37 GE "':OCONV(BEG.DATE,'D2/'):'"'
                  STMT:=' AND WITH 37 LE "':OCONV(END.DATE,'D2/'):'"'
                  STMT :=' AND WITH 280'
                  EXECUTE STMT PASSLIST NDX.LIST RTNLIST BILL.LIST CAPTURING OUTPUT
               END
               NUM.BILLS=@SELECTED
               TOT.NUM.BILLS+=NUM.BILLS
               CRT @(0,10):@(-3):' #Bills - ':NUM.BILLS'R#12':' - ':TOT.NUM.BILLS'R#15'
               BILL.EOF=0
               BILL.CNT=0
               BILL.PER=0
               LOOP
                  READNEXT BILL.ID FROM BILL.LIST ELSE BILL.EOF=1
               UNTIL BILL.EOF DO
                  BILL.CNT+=1
                  BILL.PCT=ICONV(BILL.CNT/NUM.BILLS*100,'MR2')
                  *
**                  IF NOT(REM(BILL.CNT,100)) THEN
                  CRT @(0,10):@(-3):' #Bills - ':NUM.BILLS'R#12':' - ':BILL.CNT'R#15'
**                  END
                  MATREAD BILL.REC FROM F.BILL,BILL.ID THEN

                     CARRIER.ID=FIELD(BILL.ID,'*',1)
                     PRO=FIELD(BILL.ID,'*',2)
                     VERSION=FIELD(BILL.ID,'*',3)
                     IF VERSION GT 2 THEN CONTINUE

                     IF BILL.REC(37)='' THEN
                        ERRORS<-1>='Missing Process Date for ':BILL.ID
                        ****       RETURN TO THE.END
                        CONTINUE
                     END

                     IMAGE.NO = BILL.REC(280)
                     SEQ.NO = BILL.REC(290)
                     VIN=""
                     VIN<1> = IMAGE.NO
                     IF BILL.REC(39) = "R" THEN
                        VIN<2> = "REJECTED"
                     END ELSE
                        VIN<2> = "PROCESSED"
                     END
                     VIN<3> = PRO
                     VIN<4> = SEQ.NO
                     CALL SEND.IMG.PROC.REST(VIN,VOUT)

                     IF MOD(BILL.CNT,10)=0 THEN
                        **        CRT @(0,22):'Sleeping...zzz...zzz...':
                        ******        CRT @(0,22):@(-4):
                     END
                  END
SKIP.BILL:        *
               REPEAT

               IF TOT.NUM.BILLS+0#0 THEN
                  ******             CRT @(0,22):@(-3):
               END
            END
         END
SKIP.CLIENT:*
      REPEAT
*****************************************************************
THE.END:***
****************************************************************

      IF ERRORS#'' THEN
         ERROR.CNT+=1
         IF ERROR.CNT>3 THEN
            MVIN=''
            MVIN<1>='UPD.SQL.Group@afs.net'
            MVIN<4>='AFS_UPD.SQL.FBHIST.SUB'
            MVIN<5>='SQL Client Update Errors'
            TEXT='On ':DATE()'D2/':' ':OCONV(TIME(),'MTHS'):', ':USER:' updated '
            TEXT<1,-1>='Client ':CLIENT.ID:', Bill ':BILL.ID:', but did not succeed in updating SQL due to:'
            TEXT<1,-1>=' '
            TEXT<1,-1>=ERRORS
            MVIN<6>=TEXT
            MVIN<7>=1
            CALL SENDMAIL(MVIN,MVOUT)
         END ELSE
            **    	WRITE ERRORS ON F.ERR,"SQL.FBHIST":TIMEDATE()

         END
      END

      VIN1=''
      VIN1<1> = "FB.PROC.REST"
      VIN1<2> = USER
      VIN1<3> = SYSTEM(18)
      VIN1<4> = "E"
      **    CALL PROGTRACK(VIN1,VOUT1)

      STOP

******************************************************
OPEN.FILES:
********************************************************

      OPEN '','FB.TABLES' TO F.TABLES ELSE
         CALL OPEN.ABORT("FB.TABLES",PROG.NAME)
      END
      OPEN '','CLIENTS' TO F.CLIENT ELSE ABORT 201,'CLIENTS'
      OPEN '','ERRORS.LOG' TO F.ERR ELSE ABORT 201,'ERRORS.LOG'
      RETURN
   END
